### ISSUE TITLE
Not talking about 'cosmetics': Code quality

### ISSUE THREAD

**Issue by dominikzietlow** [Zhiyuan1991/proVLAE#1]
Hi guys,

I really appreciate that you release the code of your architecture that, admittedly, shows incredible results! 

Please, for the sake of making this code useful for fellow researchers (and as such a contribution to the field), invest some time to clean up the code, delete redundancies, empty import statements (e.g. pytorch and tensorflow in the same file), give proper variable- and method-names and so on. The code in its current state is very hard to work with.

In my opinion, the unquestionably high quality of the paper published at a top tier conference, does not reflect in the quality of this repository!

![Filing a report](https://media1.tenor.com/images/72d69b625069969f0c4784adfd5fcd06/tenor.gif)

**Comment by Zhiyuan1991** [comment]
Hi Dominik, we’re sorry that the code was not as easy to use as intended. Although rather than dumping it online, we did try our best to clean up the codes and have it tested by other users, before it was released. We appreciate your additional feedback and we will work on that to make our codes better.

The pytorch module is only used for computing MIG metrics by re-using codes from other works (included in license). Training and results visulization should have no problem to run in tensorflow alone. We will double-check those variable and function names, and add more detailed documentations for them.

Thanks!

**Comment by dominikzietlow** [comment]
Hi!

Thanks for your rapid response and apologies for the slightly heated formulation - it included a lot of overall frustration with the inconsistency of code bases in our field.

On a more constructive note: 
 - There are method names as '_' which, even for if for internal use only, deserve proper names
 - There are MIG implementations for TF as well (see [disentanglement_lib](https://github.com/google-research/disentanglement_lib))
 - The two files model_ladder_pro_celbA.py and model_ladder_progress.py are super redundant, maybe consider joining them and parameterize the differences
 - Try to produce DRY (don't repeat yourself) code
 - Consider switching to tensorflow estimator API, it will also make the whole code cleaner, gets rid of the session handling and so on (also, once you have it set up with a model_fn it's super easy to transfer into other tf based code bases)!
 - Typos here and there in the code

Since your work may well turn out to be THE baseline for learning of disentangled representations, I would be very happy to see an improved code base! 

Again apologies for the phrasing of my initial issue.
Many thanks,
Dominik
